### ISSUE TITLE
post proessor crashed

### ISSUE THREAD

**Issue by CUEBoxer** [NatLabRockies/OpenStudio-analysis-spreadsheet#11]
This is the error I get from the Cloud on a datapoint failure:

[18:26:44.347878 ERROR] Found error in state 'postprocess' with message
"[#RuntimeError: Runner error /home/ubuntu/.bundler/ruby/2.0.0/OpenStudio-workflow-gem-815e3747c9cd/lib/openstudio/workflow/jobs/run_postprocess/run_postprocess.rb failed with undefined local variable or method `analysis_dir' for #<RunPostprocess:0x00000004d88ae8"

Any ideas?

Thanks!

**Comment by nllong** [comment]
good catch. I'm not sure why we haven't seen this before, but I fixed this it in the upstream [workflow repo](https://github.com/NREL/OpenStudio-workflow-gem/commit/056982e38db202fe9bf6fcb5e0ad2d5ec6bbdd9f#diff-12018cddccf7ff156cf3a6cf6f0cb37a).  If you are using AWS, then the next time you create a cluster it should automatically pull in the changes. If you are running via vagrant, then do a configure server and configure worker.
