### ISSUE TITLE
Post Processor output is NA

### ISSUE THREAD

**Issue by CUEBoxer** [NatLabRockies/OpenStudio-analysis-spreadsheet#12]
![image](https://cloud.githubusercontent.com/assets/6518490/4396309/bd852076-4433-11e4-9b6b-d29102426dfd.png)

The analysis seems to be running now, with successful completion, but outputs are not returning values. The image above is a fraction of the warnings that came out for failed Queries for post processing.

Thanks again!

**Comment by nllong** [comment]
did this run in PAT?

**Comment by CUEBoxer** [comment]
Yes in PAT, and also was running (briefly) on the Analysis Spreadsheet in July

**Comment by rHorsey** [comment]
Closing due to 2014 datestamp. Please re-open if this is still an issue @CUEBoxer.

Cheers,
