### ISSUE TITLE
Exporting project does not check for Distribution field

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/OpenStudio-analysis-spreadsheet#19]
I had forgot to enter distribution for a variable so it was empty, export appended "_uncertain" to the empty string and then proceeded but the analysis failed.  I then set it to 'Uniform' and the same thing happened.  Finally I changed this to 'uniform' and things worked.  I thought these types of errors were caught on export.

**Comment by rHorsey** [comment]
This is part of the process of deprecating the _uncertain text in distribution field names. I'm actually going to move this issue to the analysis-gem repo, as it is based in that code.

**Comment by rHorsey** [comment]
This issue was moved to NREL/OpenStudio-analysis-gem#17
