### ISSUE TITLE
Have to enter mean and std dev for uniform distributions

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/OpenStudio-analysis-spreadsheet#2]
@brianlball I am entering this here as I'm sure this will trip up other users too

**Comment by rHorsey** [comment]
Please note that at present all distributions require all fields to be filled out. This is a know issue, and will be dealt with in a future release. Until such time please put in numerical values for all fields, even if they make absolutely no sense. Thanks!

**Comment by rHorsey** [comment]
This issue was moved to NREL/OpenStudio-analysis-gem#18
