### ISSUE TITLE
images for readme.md

### ISSUE THREAD

**Issue by brianlball** [NatLabRockies/OpenStudio-analysis-spreadsheet#20]
![architecture](https://cloud.githubusercontent.com/assets/2235296/10324109/764a00e8-6c44-11e5-8e96-828a06c8df63.png)
![calibration](https://cloud.githubusercontent.com/assets/2235296/10324111/7887be68-6c44-11e5-86de-9d004585ad8e.png)
![optimization](https://cloud.githubusercontent.com/assets/2235296/10324114/7a4e536a-6c44-11e5-9c64-57ef26658ed3.png)
![parallel_coord](https://cloud.githubusercontent.com/assets/2235296/10324117/7bc4e34e-6c44-11e5-8bee-894b4412043d.png)
![temp_calibrate](https://cloud.githubusercontent.com/assets/2235296/10324119/7d4919ce-6c44-11e5-982a-2216095b523d.png)
![temp_calibrate2](https://cloud.githubusercontent.com/assets/2235296/10324120/7ec41f60-6c44-11e5-941d-208286a63b32.png)
![uq](https://cloud.githubusercontent.com/assets/2235296/10324123/802cc5fa-6c44-11e5-86d8-c8db0302d514.png)

**Comment by rHorsey** [comment]
Not an issue, but a feature!

**Comment by brianlball** [comment]
in order for the graphics to show up in the readme, its suggested to make an issue and put them here so you can reference them in the readme.  This issue is just a dummy placeholder for graphics

**Comment by rHorsey** [comment]
Very cool - this should be fine closed.
