### ISSUE TITLE
cli.rb check aws access up front

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/OpenStudio-analysis-spreadsheet#23]
If I forget to sign in to NREL's Developer VPN and submit a job, I get a connection timed out error when the analysis.zip file is being uploaded. However, this occurs after spinning up the AWS instances (and a bunch of other processing stuff) which means that it cost me money and, more importantly, I wasted 20 minutes before I found out. Or sometimes I've wasted an entire afternoon because I walked away from my desk before the error occurred.

Is it possible to try a connection to AWS up front in the cli.rb script and bail out if it fails?

Here's the error I get when not signed into DevVPN:
![untitled](https://cloud.githubusercontent.com/assets/5861765/15974731/3db1a9a8-2f07-11e6-8b38-8d6b226101d0.png)

**Comment by brianlball** [comment]
This looks like its an analysis-gem issue.  The timeout is on submitting the .zip file to the server.  Are you using the latest gem?  Check out this commit where i was dealing with a similiar issue. https://github.com/NREL/OpenStudio-analysis-gem/commit/0024c290575c33628b3bb6b4e8f7ddb69497fff8

**Comment by shorowit** [comment]
The length of the timeout is not the issue, NREL blocks access when not using DevVPN.

**Comment by brianlball** [comment]
but it looks like the cluster was successfully created and it timed out on uploading the analysis.zip and json

**Comment by shorowit** [comment]
Yes, it always occurs when uploading those files. It's 100% reproducible when I'm at NREL (whereas it always works perfectly when I'm at home or using DevVPN).

**Comment by shorowit** [comment]
I went from being able to reproduce this 100% of the time to not being able to reproduce this.
