### ISSUE TITLE
bundle exec rake run fails

### ISSUE THREAD

**Issue by AntoineDao** [NatLabRockies/OpenStudio-analysis-spreadsheet#27]
Get the following error when running the script locally: 
![image](https://user-images.githubusercontent.com/20436635/32908447-8240b898-cafb-11e7-8f9a-4ae2228f702a.png)

Completely new to Ruby (not other languages though) so hoping this is not too much of a noob fix. Apologies in advance if this is a non issue but would appreciate help!

**Comment by brianlball** [comment]
have you done:
>gem install bundler
>bundle

looks like you are missing some gems

**Comment by AntoineDao** [comment]
Yes there was indeed something missing. Laptop uses new microsoft VPN system which seems to be difficult to circumvent. Can get this working on any VM or personal laptopt though. Thanks for the help and sorry for the false alarm!

**Comment by brianlball** [comment]
hmmm, check out the proxy section in the wiki, maybe that will help with the vpn issues.
Best!
