### ISSUE TITLE
Cluster not configured

### ISSUE THREAD

**Issue by ranchhand6** [NatLabRockies/OpenStudio-analysis-spreadsheet#8]
When I try to "bundle exec rake run", I get the following error:

Aws::EC2::Errors::Unsupported: Your requested instance type (m3.medium) is not supported in your requested Availability Zone (us-east-1c). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1e, us-east-1d.

I have played around with trying to get the rake file to point to another region without much luck.  I suspect this is perhaps a key pair misconfiguration, but I think I have the right permissions on the keys.

These are policies I have applied to the keys.

AmazonEC2FullAccess
PowerUserAccess

Am I missing something?

**Comment by nllong** [comment]
Sorry for the troubles.  In order to stand up the cluster we have to make sure that the systems are in the same availability zone.  I have yet to see this specific issue.  Could you try running the request with a different instance type (i.e. m3.large or m2.2xlarge)?

**Comment by ranchhand6** [comment]
I think I've gotten beyond it.  I ended up a commit or two behind when I cloned the repository last week for some reason, and doing a "git pull origin master" picked up the changes that were made to update for new server types in AWS.  I had to futz around a little with Gemfile dependencies, but in the end it looks like it's working.

Thanks for the quick response, sorry for the false alarm!

**Comment by ranchhand6** [comment]
This came back, happens with multiple ami sizes:

bundle exec rake run

Select which project to run from the list below:
Note: if this list is too long, simply remove xlsx files from the ./projects directory
  1) template_lhs_discrete_continuous.xlsx
  2) template_nsga.xlsx
  3) template_optim.xlsx
  4) template_rgenoud.xlsx
  5) training_lhs1.xlsx
  6) training_lhs2.xlsx

Selection (1-6): 2
    Warning: 'add_overhangs_by_projection_factor:construction' static value was empty or null, assuming optional and skipping
Creating JSON and ZIP file for NSGA Template:large office
  Adding measure /Users/tonydenn/Development/rails/OpenStudio-analysis-spreadsheet/measures/ReduceLightingLoadsByPercentage to zip file
  Adding measure /Users/tonydenn/Development/rails/OpenStudio-analysis-spreadsheet/measures/RotateBuilding to zip file
  Adding measure /Users/tonydenn/Development/rails/OpenStudio-analysis-spreadsheet/measures/IncreaseInsulationRValueForExteriorWalls to zip file
  Adding measure /Users/tonydenn/Development/rails/OpenStudio-analysis-spreadsheet/measures/IncreaseInsulationRValueForRoofs to zip file
  Adding measure /Users/tonydenn/Development/rails/OpenStudio-analysis-spreadsheet/measures/SetWindowToWallRatioByFacade to zip file
  Adding measure /Users/tonydenn/Development/rails/OpenStudio-analysis-spreadsheet/measures/AddOverhangsByProjectionFactor to zip file
  Adding measure /Users/tonydenn/Development/rails/OpenStudio-analysis-spreadsheet/measures/AdjustTheromstatSetpointsByDegrees to zip file
  Adding measure /Users/tonydenn/Development/rails/OpenStudio-analysis-spreadsheet/measures/SetChilledWaterLoopTemperature to zip file
  Adding measure /Users/tonydenn/Development/rails/OpenStudio-analysis-spreadsheet/measures/SetHotWaterLoopTemperature to zip file
  Adding measure /Users/tonydenn/Development/rails/OpenStudio-analysis-spreadsheet/measures/XcelEDATariffSelectionandModelSetup to zip file
Creating cluster for default_cluster
Validating cluster options
Number of worker nodes set to 1
Starting cluster...
rake aborted!
Aws::EC2::Errors::Unsupported: Your requested instance type (m3.xlarge) is not supported in your requested Availability Zone (us-east-1c). Please retry your request by not specifying an Availability Zone or choosing us-east-1e, us-east-1d, us-east-1a.
/Users/tonydenn/Development/rails/OpenStudio-analysis-spreadsheet/Rakefile:101:in `create_cluster'
/Users/tonydenn/Development/rails/OpenStudio-analysis-spreadsheet/Rakefile:339:in`block in <top (required)>'
Tasks: TOP => run
(See full trace by running task with --trace)

**Comment by rHorsey** [comment]
I believe from the 2014 datestamp that this issue has been dealt with. If not please re-open @ranchhand6 

Cheers

**Comment by ranchhand6** [comment]
We moved on to another solution, no longer an issue for us.  I can't verify
if this has been fixed or not.

T

**Comment by rHorsey** [comment]
@ranchhand6  We're sorry to hear that! It looks like our new implementation of the AWS gem should work more elastically for deployment in the future, but there's no test like other people using your code. If you circle back around to this repo and run into issues please let us know!
