### ISSUE TITLE
bundler Ruby Gem error: <AutoScaling.api.json>

### ISSUE THREAD

**Issue by CUEBoxer** [NatLabRockies/OpenStudio-analysis-spreadsheet#9]
I get this error when trying "bundle exec rake run" within GitBash

![working_openstudio-analysis-spreadsheet-0 3_gem error](https://cloud.githubusercontent.com/assets/6518490/4310447/75dbf6f6-3ea6-11e4-8374-b14209f51f5e.jpg)

**Comment by brianlball** [comment]
There is a problem with the aws-sdk.rc15 gem.  We have reverted back to rc14.
Delete your gemfile.lock and do a pull to make sure your repo is up to date.
